name: Publish distributions to PyPI or TestPyPI

on:
  push:
    branches:
      - main

jobs:
  build-n-publish:
    name: Build and publish Python distributions to PyPI or TestPyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install twine
      run: |
        python -m pip install -U pip
        python -m pip install -U twine wheel build

    - name: Build a tar ball
      run: |
        python -m build --sdist --wheel

    - name: Verify the distributions
      run: twine check dist/*

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
